## 【課題1】内積を手計算しよう


$$
    \boldsymbol{A} =
        \left[\begin{array}{ccc}
            -1 & 2 & 3 \\
            4 & -5 & 6 \\
            7 & 8 & -9 \\
        \end{array}\right] \quad,
    \boldsymbol{B} =
        \left[\begin{array}{ccc}
            0 & 2 & 1 \\
            0 & 2 & -8 \\
            2 & 9 & -1 \\
        \end{array}\right] \quad
$$


よって、


$$
    \boldsymbol{A * B} =
        \left[\begin{array}{ccc}
            6 & 29 & -20 \\
            12 & 52 & 38 \\
            -18 & -51 & -48 \\
        \end{array}\right] \quad
$$

In [48]:
# compute an inner product of single arrays

import numpy as np

A = np.array([[-1,2,3], [4,-5,6], [7,8,-9]])
B = np.array([[0,2,1], [0,2,-8], [2,9,-1]])

ele00 = 0
for _ in range(3):
    item = A[0][_] * B[_][0]
    ele00 += item

ele00

6

In [50]:
# compute an inner product of multidimensional arrays by "for"

ans = []
for k in range(3):
    for j in range(3):
        ele = 0
        for i in range(3):
            ele += A[k][i] * B[i][j]
        ans.append(ele)

np.array(ans).reshape(3,3)

array([[  6,  29, -20],
       [ 12,  52,  38],
       [-18, -51, -48]])

In [51]:
# compute an inner product of multidimensional arrays by np.dot

np.dot(A,B)

array([[  6,  29, -20],
       [ 12,  52,  38],
       [-18, -51, -48]])

## 【課題5】内積ができないときはどうするか


$$
    \boldsymbol{A} =
        \left[\begin{array}{ccc}
            -1 & 2 & 3 \\
            4 & -5 & 6 \\
        \end{array}\right] \quad,
    \boldsymbol{B} =
        \left[\begin{array}{ccc}
            -9 & 8 & 7 \\
            6 & -5 & 4 \\
        \end{array}\right] \quad
$$


行列 $ A * B $ が計算できない理由は、行列 $ A $ の列数と、行列 $ B $ の行数が同じでないため。

In [54]:
# # compute an inner product of multidimensional arrays by transposing

A = np.array([[-1,2,3], [4,-5,6]])
B = np.array([[-9,8,7], [6,-5,4]])

np.dot(A,B.T)

array([[ 46,  -4],
       [-34,  73]])