## 【課題$1$】内積を手計算しよう


$$
    \boldsymbol{A} =
        \left[\begin{array}{ccc}
            -1 & 2 & 3 \\
            4 & -5 & 6 \\
            7 & 8 & -9 \\
        \end{array}\right] \quad,
    \boldsymbol{B} =
        \left[\begin{array}{ccc}
            0 & 2 & 1 \\
            0 & 2 & -8 \\
            2 & 9 & -1 \\
        \end{array}\right] \quad
$$


よって、


$$
    \boldsymbol{A * B} =
        \left[\begin{array}{ccc}
            6 & 29 & -20 \\
            12 & 52 & 38 \\
            -18 & -51 & -48 \\
        \end{array}\right] \quad
$$

## 【課題$2$】$1$次元配列の内積をfor文で計算しよう


まずは、ご自身で配列のindexを指定し、


- 行列$A$の$(0,0)$の要素と行列$B$の$(0,0)$の要素を掛け合わせる


- 行列$A$の$(0,1)$の要素と行列$B$の$(1,0)$の要素を掛け合わせる


- 行列$A$の$(0,2)$の要素と行列$B$の$(2,0)$の要素を掛け合わせる


- それらの値を全て足し合わせる


のフローをfor文を使って計算してください。

In [48]:
# compute an inner product of single arrays

import numpy as np

A = np.array([[-1,2,3], [4,-5,6], [7,8,-9]])
B = np.array([[0,2,1], [0,2,-8], [2,9,-1]])

ele00 = 0
for _ in range(3):
    item = A[0][_] * B[_][0]
    ele00 += item

ele00

6

## 【課題$3$】多次元配列の内積をfor文で計算しよう


for文を使って行列$A$、$B$の積を計算しましょう！【課題$2$】では$(0,0)$のみ計算していただきましたが、全て計算してください。

> ヒント  
indexの移行は行方向と列方向があるので、【課題$2$】で実装していただいたコードに加えて、さらに$2$回for文が必要になります。

In [50]:
# compute an inner product of multidimensional arrays by "for"

ans = []
for k in range(3):
    for j in range(3):
        ele = 0
        for i in range(3):
            ele += A[k][i] * B[i][j]
        ans.append(ele)

np.array(ans).reshape(3,3)

array([[  6,  29, -20],
       [ 12,  52,  38],
       [-18, -51, -48]])

## 【課題$4$】内積をnp.dotで計算しよう


np.dot($A$,$B$)を計算して、【課題$3$】と同じになることを試してください。

In [51]:
# compute an inner product of multidimensional arrays by np.dot

np.dot(A,B)

array([[  6,  29, -20],
       [ 12,  52,  38],
       [-18, -51, -48]])

## 【課題5】内積ができないときはどうするか


以下のような例を考えます。


$$
    \boldsymbol{A} =
        \left[\begin{array}{ccc}
            -1 & 2 & 3 \\
            4 & -5 & 6 \\
        \end{array}\right] \quad,
    \boldsymbol{B} =
        \left[\begin{array}{ccc}
            -9 & 8 & 7 \\
            6 & -5 & 4 \\
        \end{array}\right] \quad
$$


行列$A*B$を計算しようとすると、エラーが出て計算できません。なぜエラーが出るのか理由を記載してください。


行列 $ A * B $ が計算できない理由は、行列 $ A $ の列数と、行列 $ B $ の行数が同じでないため。

そして、行列$A$、$B$のどちらかにある操作をするとエラーが出ずに計算できます。

自分である操作を施し、内積を計算してください。

In [54]:
# # compute an inner product of multidimensional arrays by transposing

A = np.array([[-1,2,3], [4,-5,6]])
B = np.array([[-9,8,7], [6,-5,4]])

np.dot(A,B.T)

array([[ 46,  -4],
       [-34,  73]])