# Object-oriented


## 【問題1】これまで利用してきたクラスの列挙


クラスを使う際はインスタンス化を行うことと、クラスの命名法がわかりました。この情報を元に、これまでの課題で利用してきたコードの中でどのようなクラスがあったかを答えてください。


最低でもPandas、matplotlib、scikit-learnからそれぞれ1つ以上見つけてください。

    - Week4授業前課題1では，

    - Week4授業前課題2では，scikit-learnからそれぞれ，線形回帰，SVM，決定木，ランダムフォレストを行うためのクラスLinearRegression，SVR，DecisionTreeClassifier，RandomForestClassifierを使用した．

## 【問題2】
## これまで利用してきたメソッドやインスタンス変 数の列挙


これまでの課題で利用してきたコードの中でどのようなメソッドやインスタンス変数があったかを答えてください。


最低でもそれぞれ5つ以上答えてください。


    - Week4授業前課題1では，
    
    - Week4授業前課題2では，fitメソッドとpredictメソッドがあった．

# Sklearn's StandardScaler

In [1]:
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.datasets import load_iris

In [2]:
# get a dataset of irises

data = load_iris()

data

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [3]:
# let X the top 10 raws of the dataset

X = data.data[:10]

X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1]])

In [4]:
# instantiating

scaler = StandardScaler()

scaler

StandardScaler(copy=True, with_mean=True, with_std=True)

In [5]:
# fit method

scaler.fit(X)

StandardScaler(copy=True, with_mean=True, with_std=True)

In [6]:
# check the 2 instance variables

print("平均:", scaler.mean_)
print("分散:", scaler.var_)

平均: [4.86 3.31 1.45 0.22]
分散: [0.0764 0.0849 0.0105 0.0056]


In [7]:
# standardizing

X_std = scaler.transform(X)

X_std

array([[ 0.86828953,  0.65207831, -0.48795004, -0.26726124],
       [ 0.14471492, -1.06391725, -0.48795004, -0.26726124],
       [-0.57885968, -0.37751902, -1.46385011, -0.26726124],
       [-0.94064699, -0.72071813,  0.48795004, -0.26726124],
       [ 0.50650222,  0.99527742, -0.48795004, -0.26726124],
       [ 1.95365143,  2.02487476,  2.43975018,  2.40535118],
       [-0.94064699,  0.3088792 , -0.48795004,  1.06904497],
       [ 0.50650222,  0.3088792 ,  0.48795004, -0.26726124],
       [-1.66422159, -1.40711636, -0.48795004, -0.26726124],
       [ 0.14471492, -0.72071813,  0.48795004, -1.60356745]])

## [Task 3] Create the StandardScaler from Scratch


I am going to create the "fit" method and the "transform" method of the class, "StandardScaler" with using "NumPy" and so on, not "scikit-learn".

In [30]:
# create a class

class ScratchStandardScaler():
    """
    標準化のためのクラス

    Attributes
    ----------
    mean_ : 次の形のndarray, shape(n_features,)
        平均
    var_ : 次の形のndarray, shape(n_features,)
        分散
    """
    
    def fit(self,X):
        """
        標準化のために平均と標準偏差を計算する。

        Parameters
        ----------
        X : 次の形のndarray, shape (n_samples, n_features)
            学習データ
        """
        
        self.mean_ = np.mean(X)
        self.var_ = np.var(X)
        
        
    def transform(self,X):
        """
        fitで求めた値を使い標準化を行う。

        Parameters
        ----------
        X : 次の形のndarray, shape (n_samples, n_features)
            特徴量

        Returns
        ----------
        X_scaled : 次の形のndarray, shape (n_samples, n_features)
            標準化された特緒量
        """
        
        X_scaled = (X-self.mean_) / np.sqrt(self.var_)
        return X_scaled

In [9]:
# check the class, "ScratchStandardScaler"

# init the class, "ScratchStandardScaler"
scratch_scaler = ScratchStandardScaler()

scratch_scaler

In [10]:
# check the def, "fit"

scratch_scaler.fit(X)

In [11]:
# check the result of the def, "fit"

print("平均:", scratch_scaler.mean_)
print("分散:", scratch_scaler.var_)

平均: 2.46
分散: 3.1744


In [12]:
# check the def, "transform"

X_std = scratch_scaler.transform(X)

X_std

array([[ 1.48174374,  0.58371723, -0.59494256, -1.26846245],
       [ 1.36949043,  0.30308395, -0.59494256, -1.26846245],
       [ 1.25723711,  0.41533726, -0.65106922, -1.26846245],
       [ 1.20111046,  0.3592106 , -0.53881591, -1.26846245],
       [ 1.42561708,  0.63984389, -0.59494256, -1.26846245],
       [ 1.65012371,  0.80822386, -0.42656259, -1.15620913],
       [ 1.20111046,  0.52759057, -0.59494256, -1.21233579],
       [ 1.42561708,  0.52759057, -0.53881591, -1.26846245],
       [ 1.08885714,  0.24695729, -0.59494256, -1.26846245],
       [ 1.36949043,  0.3592106 , -0.53881591, -1.3245891 ]])

# ExampleClass


## [Task 4] Create a Class for Four Arithmetic Operations


I am going to create a class for four arithmetic operations. Additionally, I will add warning statements in a case that values input on the constructor are character strings, arrays or something like that except for numbers, and then add a code, "self.value=0".

In [40]:
# create a class

class ExampleClass():
    """
    説明用の簡単なクラス

    Parameters
    ----------
    value : float or int
        初期値

    Attributes
    ----------
    value : float or int
        計算結果
    """
    
    def __init__(self,value):
        if str(value).isdigit() == True or type(value) == float:
            self.value = value
            print("初期値{}が設定されました".format(self.value))
        else:
            print("入力された'{}'は，数値ではありません".format(value))
            self.value = 0
    
    
    def add(self,value2):
        """
        受け取った引数をself.valueに加える
        """
        
        self.value += value2
    
    
    def subtract(self,value3):
        self.value -= value3
    
    
    def multiple(self,value4):
        self.value *= value4
    
    
    def devide(self,value5):
        self.value /= value5

In [41]:
# check the class

example = ExampleClass(5)
print("value:", example.value)

example.add(3)
print("value:", example.value)

example.subtract(1)
print("value:", example.value)

example.multiple(10)
print("value:", example.value)

example.devide(2)
print("value:", example.value)


example2 = ExampleClass(1.5)
print("value:", example2.value)


example3 = ExampleClass("あ")
print("value:", example3.value)

初期値5が設定されました
value: 5
value: 8
value: 7
value: 70
value: 35.0
初期値1.5が設定されました
value: 1.5
入力された'あ'は，数値ではありません
value: 0
